CREATE TABLE [User]
(
  UserID BIGINT NOT NULL,
  Version INT NOT NULL CONSTRAINT DF_User_Version DEFAULT(0),
  LastModifiedBy DATETIME NOT NULL,
  LastModifiedOn BIGINT NOT NULL,
  CreatedBy DATETIME NOT NULL,
  CreatedOn BIGINT NOT NULL,
  DeletedBy DATETIME NOT NULL,
  DeletedOn BIGINT NOT NULL,
  FirstName NVARCHAR (200) NOT NULL,
  LastName NVARCHAR (200) NOT NULL,
  Email NVARCHAR (200) NOT NULL,
  Password VARBINARY (100) NULL,
  Salt VARBINARY (50) NULL,
  LastChangedPasswordOn DATETIME NULL,
	CONSTRAINT PK_User PRIMARY KEY (UserID)
)